### ISSUE TITLE
Plans for index submission

### ISSUE THREAD

**Issue by cnpryer** [ddotta/awesome-polars#1]
Hi just a heads up I've been marinating one of these at https://github.com/cnpryer/awesome-polars.

Thought I'd just let you know in case it get's added to the index.

https://github.com/cnpryer/awesome-polars/issues/1

**Comment by ddotta** [comment]
Hi @cnpryer it's great, I hadn't seen it, sorry!  
No problem to add this list to the index for sure but if you prefer maybe we can put everything together in the same list? I intend to do an almost daily watch of the news related to Polars in the next weeks/months
