### ISSUE TITLE
Add youtube video Polars Introduction for Python from Jeff Heaton

### ISSUE THREAD

**Issue by Franky1** [ddotta/awesome-polars#11]
### Link to suggestion

https://www.youtube.com/watch?v=J0wpRP-ExVg

### Targeted section

Talks and videos

### Describe your suggestion

Polars Introduction for Python with a 128GB Ryzen 24-core Benchmark vs Pandas

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Many thanks @Franky1 for this suggestion!  Video has been added to the list.
