### ISSUE TITLE
Add youtube playlist Polars - Data Analysis with Python by Martin Bel

### ISSUE THREAD

**Issue by Franky1** [ddotta/awesome-polars#12]
### Link to suggestion

https://www.youtube.com/watch?v=-O2YuS0n03U&list=PLo9Vi5B84_dfAuwJqNYG4XhZMrGTF3sBx

### Targeted section

Talks and videos

### Describe your suggestion

Playlist
[Polars - Data Analysis with Python](https://www.youtube.com/playlist?list=PLo9Vi5B84_dfAuwJqNYG4XhZMrGTF3sBx)
by Martin Bel

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by Franky1** [comment]
Github repo for the playlist see here:
<https://github.com/martinbel/polars-tutorial>

**Comment by ddotta** [comment]
Thanks @Franky1 for this suggestion !
