### ISSUE TITLE
Fancy adding polars-business?

### ISSUE THREAD

**Issue by MarcoGorelli** [ddotta/awesome-polars#195]
### Link to suggestion

https://github.com/MarcoGorelli/polars-business

### Targeted section

Python

### Describe your suggestion

polars-business is a Polars plugin for doing business day arithmetic. Fancy adding it?

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Thanks @MarcoGorelli for your suggestion ! It has been added to the list !
