### ISSUE TITLE
Modern Polars 

### ISSUE THREAD

**Issue by andreale28** [ddotta/awesome-polars#2]
### Link to suggestion

https://kevinheavey.github.io/modern-polars/

### Targeted section

Tutorials & workshops

### Describe your suggestion

This is a side by side comparison between Polars and Pandas containing code in both frameworks, which I think pretty awesome. It can be viewed at a tutorial for those who intend to replace Pandas with Polars.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Many thanks for the contribution @andreale28 ! Your tutorial looks amazing !
