### ISSUE TITLE
Polars for chemistry

### ISSUE THREAD

**Issue by bertiewooster** [ddotta/awesome-polars#256]
### Link to suggestion

https://bertiewooster.github.io/2023/03/10/Revisiting-a-Classic-Cheminformatics-Paper-The-Wiener-Index.html

### Targeted section

Blog posts

### Describe your suggestion

My blog post would be the first example of using Polars for science. It uses RDKit, one of the most popular packages for cheminformatics--the processing of chemical information. It points out helpful features of Polars including struct columns and unnest, joins, when-then-otherwise, and group_by.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Thanks @bertiewooster for your suggestion ! It will be added to the list !
