### ISSUE TITLE
Polars: um simples mas prático tutorial

### ISSUE THREAD

**Issue by ddotta** [ddotta/awesome-polars#29]
### Link to suggestion

https://nbviewer.org/github/barbosarafael/polars_python_test/blob/main/01-notebook/01-polars_notebook.ipynb

### Targeted section

Tutorials & workshops

### Describe your suggestion

Tutorial in the format of an ipynb notebook that illustrates several features of Polars in Spanish by [@barbosarafael](https://github.com/barbosarafael)

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
@barbosarafael. Your ipynb will be added to the Awesome Polars List.

**Comment by barbosarafael** [comment]
@ddotta Thanks for adding the tutorial I made to your repository, which by the way is well done.

There is only one modification to the text you described in the tutorial:

> Polars: um simple but practical tutorial - Tutorial in the format of an ipynb notebook that illustrates several features of Polars in Spanish by @barbosarafael. Associated github repository is here.

The tutorial is not written in Spanish but in Portuguese (PT-BR). Do you want me to open a PR or can you reopen this issue and make this change?

**Comment by ddotta** [comment]
@barbosarafael  Yes of course sorry. I'll correct that
