### ISSUE TITLE
Add video by @prosoitos

### ISSUE THREAD

**Issue by ddotta** [ddotta/awesome-polars#295]
### Link to suggestion

https://www.youtube.com/watch?v=U5Gl_X6Z7Lk

### Targeted section

Talks and videos

### Describe your suggestion

- [DataFrames on steroids with Polars](https://www.youtube.com/watch?v=U5Gl_X6Z7Lk) ⏳ 42 min - A video that demonstrates Polars for Python and shows how much faster it is compared to pandas while remaining just as convenient by [@prosoitos](https://github.com/prosoitos). Slides are available [here](https://mint.westdri.ca/python/wb_polars_slides#/title-slide).

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
@prosoitos your presentation will be added to the awesome polars list !

**Comment by prosoitos** [comment]
Ah ah ah 😄 Cool! Thank you!
