### ISSUE TITLE
Rho Signal blogpost on Polars by Liam Brannigan

### ISSUE THREAD

**Issue by andreale28** [ddotta/awesome-polars#3]
### Link to suggestion

https://www.rhosignal.com/tags/polars/

### Targeted section

Blog posts

### Describe your suggestion

This is a series of blogpost on Polars usage which has a lot of useful tricks and information from @braaannigan. I also include website link including polars tag for easy navigation. Moreover, @braaannigan also has a [Data Analysis with Polars](https://www.udemy.com/course/data-analysis-with-polars/?couponCode=DISCOUNTCODE) course on Udemy. 

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Thanks @andreale28 for this great suggestion !

**Comment by ddotta** [comment]
@braaannigan is it ok to reference your series of Polars posts in Awesome Polars ?

**Comment by braaannigan** [comment]
@ddotta @andreale28 Yes, thanks for referencing it!

I've also made a number of youtube videos: https://www.youtube.com/channel/UC-J3uR0g7CxCSnx0YFE6R_g

Obviously, I also think it would be good to have a section for paid online courses, but I understand if you don't want to link to those!

**Comment by ddotta** [comment]
Thanks @braaannigan, I added your youtube videos. It's great !
