### ISSUE TITLE
Add video about SQL queries with Polars

### ISSUE THREAD

**Issue by ddotta** [ddotta/awesome-polars#338]
### Link to suggestion

https://www.youtube.com/watch?v=-D_tsBY4NrI

### Targeted section

Talks and videos

### Describe your suggestion

- [Polars - SQL Interface for Querying DataFrames](https://www.youtube.com/watch?v=-D_tsBY4NrI) ⏳ 20 min - A video that 
shows how to use SQL to query the data in Polars DataFrames by [@bugbytes-io](https://github.com/bugbytes-io).

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
@bugbytes-io your video will be added to the Awesome Polars List

**Comment by bugbytes-io** [comment]
Thanks for sharing that, Damien!
