### ISSUE TITLE
Polars plugins section?

### ISSUE THREAD

**Issue by MarcoGorelli** [ddotta/awesome-polars#343]
Hey - fancy adding a section for Polars plugins? We could then link to that in the plugins tutorial

**Comment by ddotta** [comment]
Sorry for the delay @MarcoGorelli 

Here's a suggested section to add to the list.
I'm not sure I have a complete list of existing plugins, so don't hesitate to contribute to the repository if you see any new ones come through.

**Comment by MarcoGorelli** [comment]
cool, thanks!
