### ISSUE TITLE
Polar Patch

### ISSUE THREAD

**Issue by Distortedlogic** [ddotta/awesome-polars#348]
### Link to suggestion

https://github.com/Summit-Sailors/polar_patch

### Targeted section

Libraries/Packages/Scripts

### Describe your suggestion

I created polar-patch to add type hinting, type checker, and IDE support for custom polars plugins. While a hot off the press alpha, I use it as my daily driver for my plugins. Id like to see it used to open up python devs to create a rich plugin ecosystem and share them more easily.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Thanks @Distortedlogic for the suggestion ! It will be added to the Awesome Polars List 🎉
