### ISSUE TITLE
Blog Post on Polars as an alternative to Pandas (with a comparison, coming from a Pandas point of view)

### ISSUE THREAD

**Issue by JohnLockwood** [ddotta/awesome-polars#4]
Hi, 

Obviously this is self-serving :), but I wonder if you'd consider adding this blog post that is only a few weeks old:

https://codesolid.com/alternatives-to-pandas-python-polars/

If you're interested I can fork and create a PR if that's easier, or just let me know.  Thanks -- great list.  Will add to a forthcoming newsletter of mine.

**Comment by ddotta** [comment]
The blog post looks great! I will add it to the list!
Many thanks 🙏 I'll try to keep it as up-to-date as possible in the coming weeks/months
