### ISSUE TITLE
Add Polars blog post by Itamar

### ISSUE THREAD

**Issue by ddotta** [ddotta/awesome-polars#48]
### Link to suggestion

https://pythonspeed.com/articles/polars-exploratory-data-analysis-vs-production/

### Targeted section

Blog posts

### Describe your suggestion

- [Polars for initial data analysis, Polars for production](https://pythonspeed.com/articles/polars-exploratory-data-analysis-vs-production/) - A blog post that shows how to use Polars for initial data analysis and then effectively in production by [@itamarst](https://github.com/itamarst).

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by itamarst** [comment]
Thanks!
