### ISSUE TITLE
DuckDB vs Polars vs Spark!

### ISSUE THREAD

**Issue by kahnwong** [ddotta/awesome-polars#52]
### Link to suggestion

https://www.karnwong.me/posts/2023/04/duckdb-vs-polars-vs-spark/

### Targeted section

Blog posts

### Describe your suggestion

This articles performs a benchmark against duckdb/polars/spark, with varying row count to see when each framework is more performant than others, with swap usage as another metric, in addition to runtime in seconds.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
Thanks @kahnwong for your suggestion. It will be added to the Awesome Polars List.
