### ISSUE TITLE
Add slides from Nico Kreiling at PyCon 2023

### ISSUE THREAD

**Issue by ddotta** [ddotta/awesome-polars#61]
### Link to suggestion

https://www.dropbox.com/s/fphay3yav2b2rdq/2023_polars.pdf?dl=1

### Targeted section

Tutorials & workshops

### Describe your suggestion

- [An opinionated introduction to Polars](https://www.dropbox.com/s/fphay3yav2b2rdq/2023_polars.pdf?dl=1) - Great Polars introduction slides from [@krlng](https://github.com/krlng) at PyCon 2023.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by krlng** [comment]
oh, very cool, thanks :-D
