### ISSUE TITLE
Add Polars-ruby

### ISSUE THREAD

**Issue by ddotta** [ddotta/awesome-polars#90]
### Link to suggestion

https://github.com/ankane/polars-ruby

### Targeted section

Require a new section (please describe below)

### Describe your suggestion

- [polars for Ruby](https://github.com/ankane/polars-ruby) - [Ruby](https://www.ruby-lang.org/en/) `polars` gems to use Polars with Ruby.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Polars__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by ddotta** [comment]
@ankane your gems has been added to the Awesome Polars List

**Comment by ankane** [comment]
Great, thanks @ddotta!
